version: '3'

services:

  db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: example
      POSTGRES_DB: multiapp

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080